export const vehicles = [
  {
    id: "NSM-2401",
    featured: true,
    year: 2024,
    make: "Riverton",
    model: "Atlas EV",
    trim: "Touring AWD",
    condition: "New",
    bodyStyle: "SUV",
    fuel: "Electric",
    drivetrain: "AWD",
    mileage: 12,
    price: 62890,
    monthlyEstimate: 889,
    exteriorColor: "#4357ad",
    interiorColor: "Sandstone",
    range: "312 mi",
    transmission: "Single-speed",
    vin: "5YJAA11A24P001401",
    stock: "2401",
    rating: 4.9,
    dealerNote: "Flagship EV with panoramic roof, adaptive suspension, and OTA updates.",
    badges: ["3D Tour", "One-Owner Demo", "Home Delivery"],
    packages: ["Tech Suite", "Cold Weather", "Premium Audio"],
    features: ["360 Camera", "Apple CarPlay", "Heated Seats", "Blind Spot Monitor", "Third Row", "Wireless Charging"],
    highlights: ["312-mile range", "12-speaker Meridian audio", "Hands-free liftgate"],
    hotspots: ["Open the panoramic roof", "Inspect second-row captain chairs", "View charging port detail"],
    availability: "Available now"
  },
  {
    id: "NSM-2314",
    year: 2023,
    make: "Aurelia",
    model: "Sierra",
    trim: "Denali Reserve",
    condition: "Used",
    bodyStyle: "Truck",
    fuel: "Gasoline",
    drivetrain: "4WD",
    mileage: 18240,
    price: 56750,
    monthlyEstimate: 803,
    exteriorColor: "#7d4e57",
    interiorColor: "Jet Black",
    range: "N/A",
    transmission: "10-Speed Auto",
    vin: "1GCPWDEK7PZ121314",
    stock: "2314",
    rating: 4.8,
    dealerNote: "Local trade with tow package, spray-in bedliner, and like-new cabin.",
    badges: ["Certified", "Price Drop", "Tow Package"],
    packages: ["Ultimate Trailer", "Safety Sense", "Premium Leather"],
    features: ["Tow Hitch", "Apple CarPlay", "Ventilated Seats", "Blind Spot Monitor", "Remote Start", "Heads-Up Display"],
    highlights: ["11,900 lb towing", "Multi-flex tailgate", "Surround vision"],
    hotspots: ["Review bed storage layout", "Inspect towing camera view", "Highlight rear seat utility"],
    availability: "Available now"
  },
  {
    id: "NSM-2219",
    year: 2022,
    make: "Monarch",
    model: "Aster",
    trim: "Sport Prestige",
    condition: "Used",
    bodyStyle: "Sedan",
    fuel: "Hybrid",
    drivetrain: "FWD",
    mileage: 26790,
    price: 34880,
    monthlyEstimate: 512,
    exteriorColor: "#2e6f57",
    interiorColor: "Stone",
    range: "48 mpg",
    transmission: "eCVT",
    vin: "JHMCV3F96NC222219",
    stock: "2219",
    rating: 4.7,
    dealerNote: "Efficient hybrid sedan with premium finish and top safety scores.",
    badges: ["Certified", "Fuel Saver"],
    packages: ["Driver Assist+", "Luxury Cabin"],
    features: ["Adaptive Cruise", "Sunroof", "Heated Seats", "Apple CarPlay", "Lane Keep Assist", "Wireless Charging"],
    highlights: ["48 mpg combined", "Leather-trimmed interior", "Bose audio"],
    hotspots: ["View digital cockpit", "Inspect rear legroom", "Show trunk opening"],
    availability: "Available now"
  },
  {
    id: "NSM-2407",
    year: 2024,
    make: "Veloce",
    model: "Corsa",
    trim: "GT Line",
    condition: "New",
    bodyStyle: "Coupe",
    fuel: "Gasoline",
    drivetrain: "RWD",
    mileage: 9,
    price: 71990,
    monthlyEstimate: 1018,
    exteriorColor: "#b94e29",
    interiorColor: "Graphite",
    range: "N/A",
    transmission: "8-Speed DCT",
    vin: "WDDZF8DB1RA240707",
    stock: "2407",
    rating: 4.9,
    dealerNote: "Performance coupe with track package, dynamic exhaust, and upgraded brakes.",
    badges: ["3D Tour", "New Arrival"],
    packages: ["Track", "Driver Vision", "Carbon Trim"],
    features: ["Apple CarPlay", "Launch Control", "Adaptive Cruise", "Blind Spot Monitor", "Heads-Up Display", "Premium Audio"],
    highlights: ["0-60 in 4.1 sec", "Performance exhaust", "Adaptive dampers"],
    hotspots: ["Check wheel and brake package", "Inspect bucket seats", "Switch paint reflections"],
    availability: "Available now"
  },
  {
    id: "NSM-2208",
    year: 2022,
    make: "Trailmark",
    model: "Summit",
    trim: "Adventure X",
    condition: "Used",
    bodyStyle: "SUV",
    fuel: "Gasoline",
    drivetrain: "AWD",
    mileage: 33440,
    price: 41290,
    monthlyEstimate: 594,
    exteriorColor: "#6d7d46",
    interiorColor: "Cocoa",
    range: "N/A",
    transmission: "9-Speed Auto",
    vin: "1C4HJXDG6NW220808",
    stock: "2208",
    rating: 4.6,
    dealerNote: "Adventure-ready SUV with roof rack, terrain modes, and upgraded all-terrain tires.",
    badges: ["Off-Road", "Home Delivery"],
    packages: ["Adventure", "Trail Vision", "Premium Sound"],
    features: ["360 Camera", "Tow Hitch", "Heated Seats", "Blind Spot Monitor", "Remote Start", "Navigation"],
    highlights: ["Terrain response modes", "Roof platform included", "All-weather mats"],
    hotspots: ["Inspect roof rack setup", "Open cargo area", "Highlight trail camera"],
    availability: "In transit"
  },
  {
    id: "NSM-2318",
    year: 2023,
    make: "Lumen",
    model: "Cityline",
    trim: "SEL",
    condition: "Used",
    bodyStyle: "Crossover",
    fuel: "Electric",
    drivetrain: "FWD",
    mileage: 11480,
    price: 38995,
    monthlyEstimate: 548,
    exteriorColor: "#5e7ce2",
    interiorColor: "Charcoal",
    range: "274 mi",
    transmission: "Single-speed",
    vin: "KNDC34LA5P5023180",
    stock: "2318",
    rating: 4.8,
    dealerNote: "Efficient urban EV crossover with low miles and rapid charging.",
    badges: ["EV", "Fast Charge"],
    packages: ["Tech", "Comfort", "Driver Assist"],
    features: ["Apple CarPlay", "Heated Seats", "Blind Spot Monitor", "360 Camera", "Wireless Charging", "Hands-Free Liftgate"],
    highlights: ["274-mile range", "Heat pump", "Level 2 charging cable included"],
    hotspots: ["View charging drawer", "Inspect slim dash layout", "Highlight rear cargo floor"],
    availability: "Available now"
  },
  {
    id: "NSM-2411",
    year: 2024,
    make: "Harbor",
    model: "Voyager",
    trim: "Platinum",
    condition: "New",
    bodyStyle: "Minivan",
    fuel: "Hybrid",
    drivetrain: "AWD",
    mileage: 14,
    price: 51440,
    monthlyEstimate: 734,
    exteriorColor: "#556270",
    interiorColor: "Pebble",
    range: "35 mpg",
    transmission: "eCVT",
    vin: "5TDYZ3DC7RS241111",
    stock: "2411",
    rating: 4.9,
    dealerNote: "Family-focused hybrid with power doors, rear entertainment, and flexible seating.",
    badges: ["3D Tour", "Family Pick"],
    packages: ["Rear Media", "Safety Elite", "Lounge Seating"],
    features: ["Third Row", "Heated Seats", "Ventilated Seats", "Apple CarPlay", "360 Camera", "Rear Entertainment"],
    highlights: ["Stow-flat third row", "Dual power sliders", "35 mpg combined"],
    hotspots: ["Open sliding door", "Inspect third-row access", "Show cargo behind third row"],
    availability: "Available now"
  },
  {
    id: "NSM-2105",
    year: 2021,
    make: "Crest",
    model: "Aurora",
    trim: "Limited AWD",
    condition: "Used",
    bodyStyle: "SUV",
    fuel: "Diesel",
    drivetrain: "AWD",
    mileage: 48210,
    price: 29770,
    monthlyEstimate: 439,
    exteriorColor: "#815355",
    interiorColor: "Ivory",
    range: "31 mpg",
    transmission: "8-Speed Auto",
    vin: "SALWR2SU7MA210505",
    stock: "2105",
    rating: 4.5,
    dealerNote: "Upscale diesel SUV with strong highway range and premium seating comfort.",
    badges: ["Value Buy", "Reduced Price"],
    packages: ["Cold Weather", "Luxury Interior", "Advanced Safety"],
    features: ["Apple CarPlay", "Heated Seats", "Blind Spot Monitor", "Panoramic Roof", "Navigation", "Tow Hitch"],
    highlights: ["Long-range diesel", "Massage front seats", "Air suspension"],
    hotspots: ["Inspect panoramic roof", "Show cargo bay", "Highlight seat controls"],
    availability: "Available now"
  }
];

export const featureOptions = [
  "Apple CarPlay",
  "360 Camera",
  "Heated Seats",
  "Blind Spot Monitor",
  "Third Row",
  "Tow Hitch",
  "Wireless Charging"
];

export const sortOptions = [
  { label: "Featured", value: "featured" },
  { label: "Price: Low to High", value: "priceAsc" },
  { label: "Price: High to Low", value: "priceDesc" },
  { label: "Mileage: Low to High", value: "milesAsc" }
];
